name: connect-backend
dependencies :
  - python=3.10.4
  - pip=22.2.2
  - psycopg2
  - pip:
      - django==4.1.1
      - djangorestframework==3.14.0
      - djangorestframework-simplejwt==5.2.1
      - flake8==5.0.4
      - gunicorn
      - pillow==9.2.0
      - django-cors-headers
      - drf-writable-nested==0.7.0
      - django-phone-field==1.8.1